foundation: CIP
url: https://cip.landscape2.io
analytics:
  gtm:
    container_id: GTM-53DPLB
colors:
  color1: rgba(32, 145, 208, 1)
  color2: rgba(5, 85, 182, 1)
  color3: rgba(32, 145, 208, 1)
  color4: rgba(32, 145, 208, 0.9)
  color5: rgba(32, 145, 208, 0.85)
  color6: rgba(52, 198, 243, 0.85)
  color7: rgba(232, 244, 250, 1)
footer:
  links:
    github: https://github.com/cip-project
    homepage: https://cip-project.org
    linkedin: https://www.linkedin.com/company/civil-infrastructure-platform/
    twitter: https://twitter.com/cip_project
  logo: https://www.cip-project.org/wp-content/uploads/sites/17/2024/07/civil-infrastructure-platform_cip_logo_white-horizontal.svg
  text: >
    Copyright © Civil Infrastructure Platform is a Linux Foundation Project. All Rights Reserved. Linux Foundation is a registered
    [trademark](https://www.linuxfoundation.org/programs/legal/trademark)</a> of The Linux Foundation. Linux is a registered trademark of Linus Torvalds. Please
    see our [privacy policy](https://www.linuxfoundation.org/privacy) and [terms of use](https://www.linuxfoundation.org/terms).
grid_items_size: large
header:
  links:
    github: https://github.com/cip-project/landscape
  logo: https://www.cip-project.org/wp-content/uploads/sites/17/2024/07/civil-infrastructure-platform_cip_logo_color-horizontal.svg
screenshot_width: 1500
