name: Build Landscape from LFX

on:
  workflow_dispatch:
  schedule:
  - cron: "0 21 * * *"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: jmertic/lfx-landscape-tools@0bf6d41e8dc473abc256fd3fbb8502c96d75587b # main
        with:
          project_processing: skip
        env:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
