name: Build Landscape from LFX

on:
  workflow_dispatch:
  schedule:
  - cron: "0 21 * * *"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: jmertic/lfx-landscape-tools@0418f62fb63f8f52cdb87648bf0a3df83a763c9d # 20241209
        with:
          project_processing: skip
        env:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
